title: Kurt W. Pasewaldt
#logo: /assets/img/logo.png
description: My site that will provide the home lab projects I am workingon. 
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
