exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: Kurt W. Pasewaldt
description: My site that will provide the home lab projects I am working on.
logo: docs/assets/briggnisr.jpg
